### PR TITLE
grouped options disable issue solved

### PR DESCRIPTION
**Pull request by Swati-rachamalla**
please review the code and suggest changes

### CODE REVIEW

**Comment by pankajparkar** [comment]
@nitinkalenk did you review it?

**Comment by nitinkalenk** [comment]
Solution is proper and its working...but if you observe we are sending just the array of json as data while using lib and later on it gets converted to standard structure we use throughout the project...So make change the disabled property of 'group option(for ex.Cat1)' there itself...Conversion to standard structure is done by a service multiselect.service.ts file...refer the service.......
Am I right @pankajparkar ?...

**Comment by pankajparkar** [comment]
@Swati-rachamalla You solved the problem, I really appreciated your efforts. But this solution degrade the performance. The reason being is, `getOptionStyle` method fires so many times (number of options * change detection cycle run) at the time of rendering an option on HTML 

> @nitinkalenk You spotted correctly, the conversion has to be done 

So you can add this `disabled` property on each object at the time of initial preparation of collection. Have a look at [`multiselect.service.ts`](https://github.com/ngx-lib/multiselect/blob/master/projects/multiselect/src/lib/services/multiselect.service.ts) code. Its pretty simple, it has few functions. I'd recommend you to have a look at `virtualOptionsGroupingFlatten` function which does get call from [`options` setter function](https://github.com/ngx-lib/multiselect/blob/master/projects/multiselect/src/lib/grouped-options/grouped-options.component.ts#L51).

**Comment by Swati-rachamalla** [comment]
please review the changes.

**Pull request merged**
